[tool.poetry]
name = "stardist_hiv"
version = "0.1.0"
description = ""
authors = ["prodgerlab"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
snakemake = "^7.30.0"
stardist = "^0.8.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
